export const VisitorDatas = [
  {
    number: "1",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "2",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "3",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "4",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "5",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "6",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "7",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "8",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "9",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "10",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "11",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
  {
    number: "12",
    visitorname: "홍길동",
    phonenumber: "010-1111-2222",
    company: "한화테크",
    carnumber: "11가 2222",
    assign: "승인",
    interviewer: "고길동",
    department: "영업 1팀",
    reservationnumber: "123456789",
    people: "2",
    visitorpurpose: "회의",
    privacyconsent: "동의",
  },
];
